apiVersion: apps/v1 #self-healing
kind: Deployment
metadata:
  name: log-generator-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator-container
        # Replace with the cloud image URI for Service A
        image: us-central1-docker.pkg.dev/gen-lang-client-0205187891/docker-workshop-repo/log_generator_image:v1
        imagePullPolicy: Always
        env:
        - name: SERVICE_B_URL
          # Use the Service name defined for the receiver; Kubernetes DNS resolves it automatically.
          value: "http://log-receiver:5000/logs"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
