apiVersion: apps/v1
###
kind: Deployment
###
metadata:
  name: log-receiver-pod
###
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-receiver
  template:
    metadata:
      labels:
        app: log-receiver
    spec:
      containers:
      - name: log-receiver-container
        ## Replace with the cloud image URI for Service B
        image: us-central1-docker.pkg.dev/gen-lang-client-0205187891/docker-workshop-repo/log_receiver_image:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: GEMINI_API_KEY
              optional: true
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
###
---
apiVersion: v1
kind: Service
metadata:
  name: log-receiver
spec:
  selector:
    app: log-receiver
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
